/* generated by unplugin-react-components */
export {}
declare global{
	const ConfirmDialog: typeof import('./common/ConfirmDialog/index')['ConfirmDialog']
	const ContentModal: typeof import('./common/ContentModal/index')['ContentModal']
	const HButton: typeof import('./common/HButton/index')['HButton']
	const PageLoading: typeof import('./common/Loading/PageLoading')['PageLoading']
	const Loading: typeof import('./common/Loading/index')['Loading']
	const MarkdownView: typeof import('./common/MarkdownPreview/index')['MarkdownView']
	const MarkdownPreview: typeof import('./common/MarkdownPreview/index')['MarkdownPreview']
	const Modal: typeof import('./common/Modal/index')['Modal']
	const Toast: typeof import('./common/Toast/index')['Toast']
	const AssetCard: typeof import('./features/AssetCard/index')['AssetCard']
	const DetailPanel: typeof import('./features/DetailPanel/index')['DetailPanel']
	const Toolbar: typeof import('./features/Toolbar/index')['Toolbar']
	const WorkCard: typeof import('./features/WorkCard/index')['WorkCard']
	const Footer: typeof import('./layout/Footer/index')['Footer']
	const MainLayout: typeof import('./layout/MainLayout/index')['MainLayout']
}